POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVqa2FsbGlvIiwiaWQiOiI2ODM1ODM5ZmY1Y2RhYjVmOGNkMDc4ODMiLCJpYXQiOjE3NDgzMzk0Mzd9.meo3JqP0wqf7hoJz0EQ7UwyyUkAOq5VJ0VqOXReeHQo

{
    "content": "token note",
    "important": false
}